import { StyleSheet, Dimensions } from 'react-native';

const { height } = Dimensions.get('window');

const stylesCopyBillsModal = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
  },
  modalContainer: {
    width: '92%',
    maxHeight: height * 0.88,
    backgroundColor: '#1c2431',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 8,
    overflow: 'hidden',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 10,
  },
  headerText: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#ffffff',
    marginBottom: 6,
  },
  headerSubtitle: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.5)',
    textAlign: 'center',
    marginBottom: 20,
  },
  section: {
    marginBottom: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: 'bold',
    color: 'rgba(255, 255, 255, 0.65)',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 10,
  },
  stepBadge: {
    backgroundColor: '#5caece',
    borderRadius: 12,
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  stepBadgeText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'rgba(255, 255, 255, 0.85)',
  },
  monthScrollContent: {
    paddingVertical: 4,
    gap: 8,
  },
  monthChip: {
    backgroundColor: 'rgba(15, 23, 42, 0.88)',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginRight: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  monthChipActive: {
    backgroundColor: '#5caece',
    borderColor: '#5caece',
  },
  monthChipText: {
    color: 'rgba(255, 255, 255, 0.55)',
    fontSize: 12,
    fontWeight: '600',
  },
  monthChipTextActive: {
    color: '#ffffff',
    fontWeight: 'bold',
  },
  selectAllButton: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: 'rgba(92, 174, 206, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(92, 174, 206, 0.4)',
  },
  selectAllText: {
    color: '#5caece',
    fontSize: 12,
    fontWeight: 'bold',
  },
  expensesContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    maxHeight: height * 0.28,
  },
  expenseItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.06)',
  },
  expenseInfo: {
    flex: 1,
    marginLeft: 4,
  },
  expenseName: {
    fontSize: 15,
    color: '#ffffff',
    fontWeight: '600',
  },
  expenseAmount: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.45)',
    marginTop: 2,
  },
  emptyContainer: {
    paddingVertical: 30,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.4)',
    fontStyle: 'italic',
    textAlign: 'center',
  },
  hintText: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.35)',
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: 16,
  },
  selectedCount: {
    fontSize: 12,
    color: '#5caece',
    fontWeight: '600',
    marginTop: 8,
    textAlign: 'center',
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    marginVertical: 4,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
    backgroundColor: '#1c2431',
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 12,
    backgroundColor: '#d9534f',
    borderRadius: 8,
    marginRight: 8,
    alignItems: 'center',
  },
  acceptButton: {
    flex: 1,
    paddingVertical: 12,
    backgroundColor: '#5caece',
    borderRadius: 8,
    marginLeft: 8,
    alignItems: 'center',
  },
  acceptButtonDisabled: {
    backgroundColor: 'rgba(92, 174, 206, 0.3)',
  },
  buttonText: {
    color: '#ffffff',
    fontWeight: 'bold',
    fontSize: 15,
  },
  loadingContainer: {
    padding: 40,
    alignItems: 'center',
  },
});

export default stylesCopyBillsModal;
