import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
  },
  headerContainer: {
    padding: 20,
    paddingBottom: 5,
    paddingTop: 'auto',
    backgroundColor: 'transparent',
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  scrollViewContent: {
    flexGrow: 1,
    padding: 20,
  },
  containerBill: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  text: {
    fontSize: 16,
  },
  icons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 60,
  },
  logoutButtonContainer: {
    padding: 20,
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderTopColor: '#ccc',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  welcomeText: {
    fontSize: 12,
    marginBottom: 5,
    textAlign: 'center',
  },
  emailText: {
    fontSize: 15,
    marginBottom: 10,
    textAlign: 'center',
  },
  bubbleContainer: {
    position: "absolute",
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 10,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    minWidth: 150,
    zIndex: 999,
  },
  bubbleOption: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
  },
  addBillButton: {
    backgroundColor: "#fff",
    borderRadius: 50,
    padding: 10,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  addBillButtonText: {
    color: '#fff',
    fontSize: 16,
  },
  addBillContainer: {
    marginTop: 10,
  },
  addBillActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  input: {
    height: 40,
    borderColor: 'gray',
    borderWidth: 1,
    marginBottom: 10,
    paddingHorizontal: 8,
  },
  billsContainer: {
    flex: 1,
    marginBottom: 70,
    backgroundColor: 'transparent',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: 300,
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 10,
    alignItems: 'center',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 20,
  },
  cancelButton: {
    backgroundColor: 'gray',
    borderRadius: 5,
    padding: 10,
  },
  rightActions: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 100,
  },
  centralContainer: {
    width: '90%',
    alignSelf: 'center',
    flex: 1,
  },
  headerLeft: {
    backgroundColor: 'red',
  },
  checkboxContainer: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    padding: 0,
    margin: 0,
  },
  customCheckboxContainer: {
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: 5,
    padding: 2,
  },
  customCheckbox: {
    fontSize: 35,
    color: '#FFD700',
  },
  textBill: {
    fontSize: 22,
    color: 'white',
    fontFamily: 'Pacifico',
    marginBottom: 5,
  },
  descriptionText: {
    fontSize: 14,
    color: '#98FB98',
    fontFamily: 'Pacifico',
    marginBottom: 5,
  },
  amountText: {
    fontSize: 20,
    color: 'black',
    fontFamily: 'Pacifico',
  },
  imageBackground: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
    opacity: 0.7,
  },
  addBillButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: 5,
    position: 'absolute',
    bottom: 20,
    right: 20,
  },
  addBillButton: {
    backgroundColor: '#5caece',
    padding: 0,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    width: 50,
    height: 50,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    marginHorizontal: 5,
  },
  addBillButtonIcon: {
    color: '#fff',
    fontSize: 30,
    alignSelf: 'center',
  },
  popoverContent: {
    position: "absolute",
    bottom: 60,
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 10,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  popoverOption: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
  },
  salaryContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 0,
    paddingTop: 4,
    paddingBottom: 2,
    borderBottomWidth: 1,
    borderBottomColor: 'black',
  },
  textContainer: {
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  amountContainer: {
    flexDirection: 'row',
    alignItems: 'center'
  },
  labelText: {
    fontWeight: 'bold',
  },
  amountText: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  amountNumber: {
    color: 'white',
  },
  amountSalary: {
    color: '#FFD700',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: '80%',
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
  },
  title: {
    marginBottom: 20,
    color: '#333',
  },
  label: {
    alignSelf: 'flex-start',
    marginBottom: 5,
    marginTop: 10,
    color: '#555',
  },
  input: {
    width: '100%',
    height: 40,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 20,
  },
  cancelButton: {
    backgroundColor: '#d9534f',
    width: '48%',
    alignItems: 'center',
    padding: 10,
    borderRadius: 5,
  },
  addButton: {
    backgroundColor: '#5caece',
    width: '48%',
    alignItems: 'center',
    padding: 10,
    borderRadius: 5,
  },
  buttonText: {
    color: 'white',
    fontWeight: 'bold',
  },

  containerAmounts: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    padding: 0,
  },
  card: {
    width: '48%',
    padding: 5,
    marginBottom: 8,
    marginTop: 8,
    borderRadius: 8,
    backgroundColor: '#f0f0f0',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  labelText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
  },
  amount: {
    fontSize: 16,
    color: '#555',
    borderRadius: 8,
    paddingHorizontal: 8,
  },
  amountText: {
    flexWrap: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  inlineText: {
    marginRight: 8,
  },
  cardContainer: {
    backgroundColor: '#ffffff',
    marginBottom: 10,
    padding: 10,
    borderRadius: 5,
    elevation: 3,
  },
  emptyText: {
    fontStyle: 'italic',
    color: 'gray',
  },
  cardContainer: {
    margin: 10,
    padding: 5,
    paddingLeft: 0,
    backgroundColor: 'white',
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 1,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    paddingLeft: 20,
    paddingTop: 5
  },
  billListContainer: {
    height: 300,
  },
  emptyText: {
    textAlign: 'center',
    color: 'gray',
  },
  carouselItem: {
    backgroundColor: '#fff',
    borderRadius: 5,
    height: 50,
    padding: 15,
    marginLeft: 25,
    marginRight: 25,
  },
  carouselText: {
    fontSize: 20,
    textAlign: 'center',
  },
  carouselContainer: {
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  yearItem: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 10,
    padding: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  yearText: {
    color: '#fff',
    fontSize: 18,
  },
  containerText: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginLeft: 1,
    marginRight: 1
  },
  text: {
    fontSize: 9,
    marginHorizontal: 5,
    color: '#333',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginLeft: 10,
    marginRight: 15,
    marginTop: 5,
    marginBottom: 5
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  flatListContainer: {
    height: 340
  },
  iconsCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  }
});
