import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
  },
  headerContainer: {
    padding: 20,
    paddingBottom: 5,
    paddingTop: 'auto',
    backgroundColor: 'transparent',
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  scrollViewContent: {
    flexGrow: 1,
    padding: 20,
  },
  containerBill: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  text: {
    fontSize: 16,
  },
  icons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 60,
  },
  logoutButtonContainer: {
    padding: 20,
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderTopColor: '#ccc',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  welcomeText: {
    fontSize: 12,
    marginBottom: 5,
    textAlign: 'center',
  },
  emailText: {
    fontSize: 15,
    marginBottom: 10,
    textAlign: 'center',
  },
  bubbleContainer: {
    position: "absolute",
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 10,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    minWidth: 150,
    zIndex: 999,
  },
  bubbleOption: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
  },
  addBillButton: {
    backgroundColor: "#fff",
    borderRadius: 50,
    padding: 10,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  addBillButtonText: {
    color: '#fff',
    fontSize: 16,
  },
  addBillContainer: {
    marginTop: 10,
  },
  addBillActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  input: {
    height: 40,
    borderColor: 'gray',
    borderWidth: 1,
    marginBottom: 10,
    paddingHorizontal: 8,
  },
  billsContainer: {
    flex: 1,
    marginBottom: 70,
    backgroundColor: 'transparent',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: 300,
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 10,
    alignItems: 'center',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 20,
  },
  cancelButton: {
    backgroundColor: 'gray',
    borderRadius: 5,
    padding: 10,
  },
  rightActions: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 100,
  },
  centralContainer: {
    width: '90%',
    alignSelf: 'center',
    flex: 1,
  },
  headerLeft: {
    backgroundColor: 'red',
  },
  checkboxContainer: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    padding: 0,
    margin: 0,
  },
  customCheckboxContainer: {
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: 5,
    padding: 2,
  },
  customCheckbox: {
    fontSize: 35,
    color: '#FFD700',
  },
  textBill: {
    fontSize: 22,
    color: 'white',
    fontFamily: 'Pacifico',
    marginBottom: 5,
  },
  descriptionText: {
    fontSize: 14,
    color: '#98FB98',
    fontFamily: 'Pacifico',
    marginBottom: 5,
  },
  amountText: {
    fontSize: 20,
    color: 'black',
    fontFamily: 'Pacifico',
  },
  imageBackground: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
    opacity: 0.7,
  },
  addBillButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: 5,
    position: 'absolute',
    bottom: 20,
    right: 20,
  },
  addBillButton: {
    backgroundColor: '#5caece',
    padding: 0,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    width: 50,
    height: 50,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    marginHorizontal: 5,
  },
  addBillButtonIcon: {
    color: '#fff',
    fontSize: 30,
    alignSelf: 'center',
  },
  popoverContent: {
    position: "absolute",
    bottom: 60,
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 10,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  popoverOption: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
  },
  salaryContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 0,
    paddingTop: 4,
    paddingBottom: 2,
    borderBottomWidth: 1,
    borderBottomColor: 'black',
  },
  textContainer: {
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  amountContainer: {
    flexDirection: 'row',
    alignItems: 'center'
  },
  labelText: {
    fontWeight: 'bold',
  },
  amountText: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  amountNumber: {
    color: 'white',
  },
  amountSalary: {
    color: '#FFD700',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: '80%',
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
  },
  title: {
    marginBottom: 20,
    color: '#333',
  },
  label: {
    alignSelf: 'flex-start',
    marginBottom: 5,
    marginTop: 10,
    color: '#555',
  },
  input: {
    width: '100%',
    height: 40,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 20,
  },
  cancelButton: {
    backgroundColor: '#d9534f',
    width: '48%',
    alignItems: 'center',
    padding: 10,
    borderRadius: 5,
  },
  addButton: {
    backgroundColor: '#5caece',
    width: '48%',
    alignItems: 'center',
    padding: 10,
    borderRadius: 5,
  },
  buttonText: {
    color: 'white',
    fontWeight: 'bold',
  },

  containerAmounts: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    padding: 0,
  },
  card: {
    width: '48%',
    padding: 5,
    marginBottom: 8,
    marginTop: 8,
    borderRadius: 8,
    backgroundColor: '#f0f0f0',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  labelText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
  },
  amount: {
    fontSize: 16,
    color: '#555',
    borderRadius: 8,
    paddingHorizontal: 8,
  },
  amountText: {
    flexWrap: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  inlineText: {
    marginRight: 8,
  },
  cardContainer: {
    backgroundColor: '#ffffff',
    marginBottom: 10,
    padding: 10,
    borderRadius: 5,
    elevation: 3,
  },
  emptyText: {
    fontStyle: 'italic',
    color: 'gray',
  },
  cardContainer: {
    margin: 10,
    padding: 5,
    paddingLeft: 0,
    backgroundColor: 'white',
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 1,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    paddingLeft: 20,
    paddingTop: 5
  },
  billListContainer: {
    height: 300,
  },
  emptyText: {
    textAlign: 'center',
    color: 'gray',
  },
  carouselItem: {
    backgroundColor: '#fff',
    borderRadius: 5,
    height: 50,
    padding: 15,
    marginLeft: 25,
    marginRight: 25,
  },
  carouselText: {
    fontSize: 20,
    textAlign: 'center',
  },
  carouselContainer: {
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  yearItem: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 10,
    padding: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  yearText: {
    color: '#fff',
    fontSize: 18,
  },
  containerText: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginLeft: 1,
    marginRight: 1
  },
  text: {
    fontSize: 9,
    marginHorizontal: 5,
    color: '#333',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginLeft: 10,
    marginRight: 15,
    marginTop: 5,
    marginBottom: 5
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  flatListContainer: {
    height: 340
  },
  iconsCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  yearSelectorContainer: {
    paddingVertical: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    borderBottomWidth: 1.5,
    borderBottomColor: 'rgba(255, 255, 255, 0.2)',
  },
  yearScrollContent: {
    paddingHorizontal: 15,
    alignItems: 'center',
  },
  yearChip: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginRight: 10,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.25)',
  },
  yearChipActive: {
    backgroundColor: '#5caece',
    borderColor: '#5caece',
    shadowColor: '#5caece',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 3,
  },
  yearChipText: {
    color: 'rgba(255, 255, 255, 0.85)',
    fontSize: 14,
    fontWeight: 'bold',
  },
  yearChipTextActive: {
    color: '#ffffff',
  },
  monthSelectorContainer: {
    paddingVertical: 12,
    marginTop: 5,
  },
  monthScrollContent: {
    paddingHorizontal: 5,
    alignItems: 'center',
  },
  monthChip: {
    backgroundColor: 'rgba(15, 23, 42, 0.88)',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginRight: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  monthChipActive: {
    backgroundColor: '#5caece',
    borderColor: '#5caece',
    shadowColor: '#5caece',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.45,
    shadowRadius: 5,
    elevation: 4,
  },
  monthChipText: {
    color: 'rgba(255, 255, 255, 0.5)',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.4,
  },
  monthChipTextActive: {
    color: '#ffffff',
    fontWeight: 'bold',
  },
  headerWrapper: {
    width: '100%',
    marginBottom: 10,
  },
  fintechCard: {
    backgroundColor: 'rgba(20, 30, 48, 0.85)',
    borderRadius: 16,
    padding: 18,
    marginHorizontal: 5,
    marginTop: 5,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 5,
  },
  fintechCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    paddingBottom: 8,
  },
  fintechCardMonth: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 1.2,
  },
  fintechCardActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sortButton: {
    padding: 6,
    marginLeft: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  fintechMainBalanceContainer: {
    alignItems: 'center',
    marginVertical: 10,
  },
  fintechBalanceLabel: {
    color: 'rgba(255, 255, 255, 0.5)',
    fontSize: 11,
    fontWeight: 'bold',
    letterSpacing: 1.5,
    marginBottom: 4,
  },
  fintechBalanceValue: {
    fontSize: 32,
    fontWeight: 'bold',
    fontFamily: 'System', // clean, modern sans-serif
  },
  fintechDetailsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
    paddingTop: 15,
  },
  fintechGridItem: {
    flex: 1,
    alignItems: 'center',
  },
  fintechGridLabel: {
    color: 'rgba(255, 255, 255, 0.4)',
    fontSize: 10,
    fontWeight: '600',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  fintechGridValue: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  sectionTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 8,
    marginBottom: 10,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  toolbarButton: {
    padding: 8,
    marginLeft: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 50,
    width: 38,
    height: 38,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  sortModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sortModalContent: {
    width: '85%',
    backgroundColor: '#1c2431',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
  },
  sortModalTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    paddingBottom: 10,
  },
  sortOptionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  sortOptionText: {
    color: 'rgba(255, 255, 255, 0.9)',
    fontSize: 15,
    marginLeft: 12,
  },
  sortModalCloseButton: {
    backgroundColor: '#5caece',
    borderRadius: 10,
    paddingVertical: 12,
    marginTop: 15,
    alignItems: 'center',
  },
  sortModalCloseText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: 'bold',
  }
});
